#!/usr/bin/env node
import path from 'node:path';
import process from 'node:process';
import { createInterface } from 'node:readline/promises';
import { analyzeProject } from './lib/analyzer.js';
import { auditUrl } from './lib/audit.js';
import { detectAgents } from './lib/detect.js';
import { doctor } from './lib/doctor.js';
import { getInstallReceipt, installPack, planInstall, uninstallPack } from './lib/install.js';
import { parseAgents } from './lib/options.js';
import { writeDesignArtifacts } from './lib/profile.js';
import { searchRegistry } from './lib/registry.js';
import type { AgentId, Scope } from './lib/types.js';

const VERSION='0.1.0';
type Opts={project?:string;agents?:string;global?:boolean;yes?:boolean;dryRun?:boolean;force?:boolean;json?:boolean;framework?:string;out?:string;browserExecutable?:string};
function help(){console.log(`Agent Design Pack ${VERSION}\n\nUsage:\n  designpack [init] [options]\n  designpack add|update|doctor|uninstall [options]\n  designpack profile [options]\n  designpack components <query> [--framework react] [--json]\n  designpack audit <url> [--out dir] [--browser-executable path] [--json]\n\nInstaller options:\n  --project <path>      Project root (default .)\n  --agents <list>       codex,claude\n  --global              User/global scope\n  --yes                 Non-interactive\n  --dry-run             Show exact planned file changes\n  --force               Back up and replace conflicts\n  --json                Machine-readable output\n`)}
function parse(argv:string[]){const opts:Opts={};const pos:string[]=[];for(let i=0;i<argv.length;i++){const a=argv[i];if(a==='--project')opts.project=argv[++i];else if(a==='--agents')opts.agents=argv[++i];else if(a==='--global')opts.global=true;else if(a==='--yes'||a==='-y')opts.yes=true;else if(a==='--dry-run')opts.dryRun=true;else if(a==='--force')opts.force=true;else if(a==='--json')opts.json=true;else if(a==='--framework')opts.framework=argv[++i];else if(a==='--out')opts.out=argv[++i];else if(a==='--browser-executable')opts.browserExecutable=argv[++i];else if(a==='--help'||a==='-h')return{help:true,opts,pos};else if(a==='--version'||a==='-V')return{version:true,opts,pos};else if(a.startsWith('-'))throw new Error(`Unknown option: ${a}`);else pos.push(a);}return{opts,pos};}
function root(p?:string){return path.resolve(p??process.cwd())}
async function chooseAgents(projectRoot:string,provided:AgentId[],yes:boolean):Promise<AgentId[]>{if(provided.length)return provided;const ds=await detectAgents(projectRoot);const detected=ds.filter(d=>d.confidence>=.55).map(d=>d.id);if(yes)return detected.length?detected:(['codex','claude'] as AgentId[]);console.log('Detected coding agents');for(const d of ds)console.log(`  ${d.confidence>=.55?'✓':d.confidence>0?'?':'○'} ${d.id} confidence ${Math.round(d.confidence*100)}%${d.version?` · ${d.version}`:''}`);const fallback=(detected.length?detected:(['codex','claude'] as AgentId[])).join(',');const rl=createInterface({input:process.stdin,output:process.stdout});const ans=await rl.question(`Install for [${fallback}]: `);rl.close();return parseAgents(ans.trim()||fallback)}
function printDoctor(cs:any[]){for(const c of cs)console.log(`${c.status==='pass'?'✓':c.status==='warn'?'!':'✗'} ${c.name}: ${c.message}`)}
async function chooseScope(opts:Opts):Promise<Scope>{if(opts.global)return'global';if(opts.yes)return'project';const rl=createInterface({input:process.stdin,output:process.stdout});const ans=(await rl.question('Install scope [project/global] (project): ')).trim().toLowerCase();rl.close();if(!ans||ans==='project'||ans==='p')return'project';if(ans==='global'||ans==='g')return'global';throw new Error(`Unknown scope: ${ans}`)}
async function confirmPlan(projectRoot:string,scope:Scope,agents:AgentId[],plan:any[],yes:boolean){if(yes)return true;console.log(`\nProject\n  ${projectRoot}\n\nScope\n  ${scope}\n\nAgents\n  ${agents.join(', ')}\n\nChanges`);const visible=plan.filter((x:any)=>x.action!=='skip');if(!visible.length)console.log('  No file changes needed.');else for(const x of visible.slice(0,40))console.log(`  ${x.action.padEnd(8)} ${x.target}`);if(visible.length>40)console.log(`  … ${visible.length-40} more`);const rl=createInterface({input:process.stdin,output:process.stdout});const ans=(await rl.question('\nContinue? [Y/n]: ')).trim().toLowerCase();rl.close();return !['n','no'].includes(ans)}
async function installCommand(opts:Opts,mode:'init'|'add'|'update'='init'){const projectRoot=root(opts.project);const scope=await chooseScope(opts);let supplied=parseAgents(opts.agents);if(mode==='update'&&!supplied.length){const prior=await getInstallReceipt(projectRoot,scope);if(prior)supplied=Object.keys(prior.adapters).filter((x):x is AgentId=>x==='codex'||x==='claude')}const agents=supplied.length?supplied:await chooseAgents(projectRoot,[],Boolean(opts.yes));const io={projectRoot,scope,agents,dryRun:Boolean(opts.dryRun),force:Boolean(opts.force)};const plan=await planInstall(io);if(opts.dryRun){console.log(opts.json?JSON.stringify({projectRoot,scope,agents,plan},null,2):plan.map(x=>`${x.action.padEnd(8)} ${x.target}`).join('\n'));return}if(!(await confirmPlan(projectRoot,scope,agents,plan,Boolean(opts.yes)))){console.log('Cancelled.');return}const result=await installPack(io);if(result.conflicts.length){console.error('Installation stopped: local/user-owned files would be overwritten.');for(const f of result.conflicts)console.error(`  ${f}`);console.error('Use --force to back them up and replace them.');process.exitCode=2;return}const checks=await doctor(projectRoot,scope);if(opts.json)console.log(JSON.stringify({projectRoot,scope,agents,receipt:result.receipt,doctor:checks},null,2));else{console.log(`✓ DesignPack installed for ${agents.join(', ')}`);printDoctor(checks)}}

async function main(){const {opts,pos,help:wantHelp,version}=parse(process.argv.slice(2)) as any;if(wantHelp){help();return}if(version){console.log(VERSION);return}const command=pos[0]??'init';
  if(['init','add','update'].includes(command)){await installCommand(opts,command as 'init'|'add'|'update');return}
  if(command==='doctor'){const cs=await doctor(root(opts.project),opts.global?'global':'project');opts.json?console.log(JSON.stringify(cs,null,2)):printDoctor(cs);if(cs.some(c=>c.status==='fail'))process.exitCode=1;return}
  if(command==='uninstall'){const r=await uninstallPack(root(opts.project),opts.global?'global':'project');console.log(opts.json?JSON.stringify(r,null,2):`${r.message}\nRemoved ${r.removed.length}; preserved ${r.preserved.length}.`);return}
  if(command==='profile'){const r=root(opts.project);const analysis=await analyzeProject(r);const written=await writeDesignArtifacts(r,analysis,!opts.force);console.log(opts.json?JSON.stringify({analysis,written},null,2):`Framework: ${analysis.project.framework}\nStyling: ${analysis.project.styling.join(', ')||'unknown'}\nWrote: ${written.length?written.join(', '):'nothing (existing profile preserved)'}`);return}
  if(command==='components'){const query=pos.slice(1).join(' ');if(!query)throw new Error('components requires a search query');const rs=await searchRegistry(query,opts.framework);if(opts.json)console.log(JSON.stringify(rs,null,2));else for(const r of rs.slice(0,10))console.log(`${r.name} [${r.source}] score=${r.score}\n  ${r.capabilities.join(', ')}\n  ${r.sourceUrl}\n  license: ${r.license.name} (${r.license.redistribution})`);return}
  if(command==='audit'){const url=pos[1];if(!url)throw new Error('audit requires a URL');const report=await auditUrl(url,path.resolve(opts.out??'.designpack/artifacts'),{executable:opts.browserExecutable});if(opts.json)console.log(JSON.stringify(report,null,2));else{const violations=report.viewports.reduce((n:number,v:any)=>n+v.accessibility.violations.length,0);const overflow=report.viewports.filter((v:any)=>v.measurable.horizontalOverflow>0).length;console.log(`Engine: ${report.engine}\nCaptured ${report.viewports.length} viewports · ${violations} accessibility findings · ${overflow} overflow viewports`)}return}
  throw new Error(`Unknown command: ${command}`);
}
main().catch(e=>{console.error(e instanceof Error?e.message:String(e));process.exitCode=1});
